### ISSUE TITLE
svg still does not render as of the newest version

### ISSUE THREAD

**Issue by doofin** [raquo/scala-dom-builder#6]

**Comment by raquo** [comment]
I assume you mean in Laminar? How does the following element render for you?

```
// import com.raquo.laminar.api.L._
// import com.raquo.laminar.api.L.{svg => s}

  div(
      "SVG!!!",
      s.svg(
        s.height := "200",
        s.width := "400",
        s.circle(
          s.cx := "200",
          s.cy := "15",
          s.r := "30",
          s.fill := "red"
        )
      )
    )
```

What browser are you using? I tried and it works for me in latest Chrome, Firefox and Safari. Please let me know if you're using a different browser and also if it works for you in one of these browsers.

**Comment by doofin** [comment]
Oh,I find it's the fault of the latest chromium,it always load the cached things ... Firefox works

**Comment by raquo** [comment]
So did you get it working in Chromium? My Chromium works fine.

**Comment by doofin** [comment]
Yeah it works after disabling cache,closing this issue
